[package]
name = "test-tokio-fairness"
version = "0.1.0"
authors = ["Alexander Polakov <a.polakov@iconic.vc>"]

[dependencies]
tokio = "0.1.8"
futures = "0.1"
tsc = "0.1"
byteorder = "1.2"
scheduler = "0.1"
mio = "0.6"